### ISSUE TITLE
Error with Text Layout after update to 6.5.0

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#5814]
I can't open data objects after update to 6.5.0 because we using the Text Layout with a rendering Class:

```
class DocumentationLink
{
    /** @var EngineInterface */
    protected $templating;

    public function __construct(EngineInterface $templating)
    {
        $this->templating = $templating;
    }

    public static function renderLayoutText($data, Concrete $object, $params): string
    {
        /** @var DocumentationLink $self */
        $self = \Pimcore::getKernel()->getContainer()->get(__CLASS__);

        return $self->templating->render(
            'template.html.twig',
            ['classIdentifier' => $object->getClassId()]
        );
    }
}
```

`Too few arguments to function DocumentationLink::__construct(), 0 passed in vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Helper/ClassResolver.php on line 28 and exactly 1 expected`

Before it is only used static with call_user_func. Now it is used the ClassResolver which would create a object from it. We can migrate to this new service feature. But maybe its against your BC thought ;)

**Comment by dvesh3** [comment]
why not use a service which also autowire your dependencies https://pimcore.com/docs/6.x/Development_Documentation/Objects/Object_Classes/Layout_Elements/Dynamic_Text_Labels.html

**Comment by blankse** [comment]
@dvesh3 Yes I will migrate to the new format. But it is a kind of BC break ;) We think we can catch the throwable in ClassResolver::resolve. I create a PR

**Comment by dvesh3** [comment]
sounds good 👍 thanks!
